/**
 * Midnight provider setup — mirrors example-counter/counter-cli/src/api.ts
 *
 * Builds the full WalletFacade + MidnightProvider from the seed phrase in .env.
 * Call getProviders() once on startup; it caches after the first build.
 */

import * as ledger from '@midnight-ntwrk/ledger-v8';
import * as compactRuntime from '@midnight-ntwrk/compact-runtime';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { inMemoryPrivateStateProvider, type InMemoryPrivateStateProvider } from './inMemoryPrivateStateProvider.js';
import { type MidnightProvider, type WalletProvider } from '@midnight-ntwrk/midnight-js/types';
import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  createKeystore,
  InMemoryTransactionHistoryStorage,
  PublicKey,
  UnshieldedWallet,
  type UnshieldedKeystore,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { getNetworkId } from '@midnight-ntwrk/midnight-js/network-id';
import { mnemonicToSeedSync } from 'bip39';
import { Buffer } from 'buffer';
import { createHmac } from 'crypto';
import * as Rx from 'rxjs';
import { WebSocket } from 'ws';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { MIDNIGHT, WALLET } from '../config.js';

// Required for GraphQL subscriptions to work in Node.js
// @ts-expect-error WebSocket polyfill
globalThis.WebSocket = WebSocket;

// Path to the ZK keys generated by compactc
const __dirname = dirname(fileURLToPath(import.meta.url));
export const ZK_CONFIG_PATH = join(__dirname, '../../../contracts/managed');

// Private state key used to identify this contract's state in storage
export const MEMORY_PRIVATE_STATE_ID = 'memoryPrivateState' as const;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface MemoryPrivateState {
  secretKey:         Uint8Array;   // owner's secret key — drives localSecretKey() witness
  contentHash:       Uint8Array;
  timestamp:         bigint;
  geoHash:           Uint8Array;
  tagCount:          bigint;
  cardanoAssetId:    Uint8Array;
  newOwnerCommit:    Uint8Array;
}

export interface BuiltProviders {
  wallet:                WalletFacade;
  walletProvider:        WalletProvider & MidnightProvider;
  unshieldedKeystore:    UnshieldedKeystore;
  shieldedSecretKeys:    ledger.ZswapSecretKeys;
  dustSecretKey:         ledger.DustSecretKey;
  privateStateProvider:  InMemoryPrivateStateProvider;
  publicDataProvider:    ReturnType<typeof indexerPublicDataProvider>;
  zkConfigProvider:      NodeZkConfigProvider<string>;
  proofProvider:         ReturnType<typeof httpClientProofProvider>;
}

// ── Cache ─────────────────────────────────────────────────────────────────────

let _providersPromise: Promise<BuiltProviders> | null = null;

export async function getProviders(): Promise<BuiltProviders> {
  if (!_providersPromise) {
    _providersPromise = buildProviders().catch((err) => {
      _providersPromise = null; // allow retry on failure
      throw err;
    });
  }
  return _providersPromise;
}

// ── Build ─────────────────────────────────────────────────────────────────────

async function buildProviders(): Promise<BuiltProviders> {
  if (!WALLET.seedPhrase) {
    throw new Error('MIDNIGHT_WALLET_SEED is not set');
  }

  // Convert BIP-39 mnemonic → 64-byte seed → hex string
  const seedBytes = mnemonicToSeedSync(WALLET.seedPhrase);
  const seedHex   = seedBytes.toString('hex');

  // Derive HD keys for all three roles from the seed
  const hdWallet = HDWallet.fromSeed(Buffer.from(seedHex, 'hex'));
  if (hdWallet.type !== 'seedOk') throw new Error('Failed to initialize HDWallet from seed');

  const derivation = hdWallet.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  if (derivation.type !== 'keysDerived') throw new Error('Failed to derive keys from seed');

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(derivation.keys[Roles.Zswap]);
  const dustSecretKey      = ledger.DustSecretKey.fromSeed(derivation.keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(derivation.keys[Roles.NightExternal], getNetworkId());
  hdWallet.hdWallet.clear();

  // Build WalletFacade
  const walletConfig = {
    networkId: getNetworkId(),
    indexerClientConnection: {
      indexerHttpUrl:  MIDNIGHT.indexer,
      indexerWsUrl:    MIDNIGHT.indexerWS,
    },
    provingServerUrl: new URL(MIDNIGHT.proofServer),
    relayURL:         new URL(MIDNIGHT.node.replace(/^http/, 'ws')),
    txHistoryStorage: new InMemoryTransactionHistoryStorage(),
    costParameters: {
      additionalFeeOverhead: 300_000_000_000_000n,
      feeBlocksMargin: 5,
    },
  };

  const wallet = await WalletFacade.init({
    configuration: walletConfig,
    shielded:   (cfg) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg) => UnshieldedWallet(cfg).startWithPublicKey(PublicKey.fromKeyStore(unshieldedKeystore)),
    dust:       (cfg) => DustWallet(cfg).startWithSecretKey(
      dustSecretKey,
      ledger.LedgerParameters.initialParameters().dust,
    ),
  });
  await wallet.start(shieldedSecretKeys, dustSecretKey);

  // Wait for sync
  console.log('[midnight-provider] Syncing wallet with network...');

  // Show sync progress while waiting — tap into state stream in parallel
  const syncDone$ = new Rx.Subject<void>();
  wallet.state().pipe(
    Rx.throttleTime(5_000, undefined, { leading: true, trailing: true }),
    Rx.takeUntil(syncDone$),
  ).subscribe((s: any) => {
    const sp = s.shielded?.state?.progress;
    const up = s.unshielded?.state?.progress;
    const dp = s.dust?.state?.progress;

    const pct = (applied: string | number, highest: string | number) => {
      const a = Number(applied ?? 0);
      const h = Number(highest ?? 0);
      if (h === 0) return '...';
      return `${Math.min(100, Math.round((a / h) * 100))}%`;
    };

    const shieldedPct   = sp ? pct(sp.appliedIndex, sp.highestIndex) : '?';
    const unshieldedPct = up ? pct(up.appliedId,    up.highestTransactionId) : '?';
    const dustPct       = dp ? pct(dp.appliedIndex, dp.highestIndex) : '?';
    const connected     = sp?.isConnected ? 'connected' : 'connecting...';

    console.log(
      `[sync] ${connected} | shielded ${shieldedPct} | unshielded ${unshieldedPct} | dust ${dustPct}`
    );
  });

  // Wait for isSynced. Shielded/dust show highestIndex=0 when the relay node rate-limits
  // our WebSocket — the relay closes with Normal Closure before providing the chain tip.
  // We MUST wait for dust to be ready (needed for DUST fee payment), so we keep retrying
  // until the relay stabilises. Log progress every 30s so startup isn't silent.
  let waitedMs = 0;
  const POLL_MS = 30_000;
  const MAX_WAIT_MS = 15 * 60 * 1000; // 15 minutes

  await new Promise<void>((resolve, reject) => {
    const check = () => {
      Rx.firstValueFrom(wallet.state()).then((s: any) => {
        if (s.isSynced) { resolve(); return; }

        const dp = s.dust?.state?.progress;
        const dustConnected = dp?.isConnected === true;
        const dustIndex = Number(dp?.appliedIndex ?? 0);

        waitedMs += POLL_MS;
        console.log(
          `[midnight-provider] Waiting for dust wallet... (${Math.round(waitedMs / 1000)}s elapsed, connected=${dustConnected}, dustIndex=${dustIndex})`
        );

        if (waitedMs >= MAX_WAIT_MS) {
          reject(new Error('Wallet sync timeout after 15 minutes — check relay connectivity'));
          return;
        }
        setTimeout(check, POLL_MS);
      }).catch(reject);
    };

    // Also resolve immediately if isSynced fires through the main stream
    Rx.firstValueFrom(wallet.state().pipe(Rx.filter((s: any) => s.isSynced)))
      .then(resolve).catch(() => {});

    setTimeout(check, POLL_MS);
  });

  syncDone$.next();
  console.log('[midnight-provider] Wallet synced');

  // Build walletProvider + midnightProvider (same object, two interfaces)
  const walletProvider = await buildWalletProvider(wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore);

  // Build remaining providers
  const zkConfigProvider = new NodeZkConfigProvider<string>(ZK_CONFIG_PATH);

  return {
    wallet,
    walletProvider,
    unshieldedKeystore,
    shieldedSecretKeys,
    dustSecretKey,
    privateStateProvider: inMemoryPrivateStateProvider(),
    publicDataProvider:  indexerPublicDataProvider(MIDNIGHT.indexer, MIDNIGHT.indexerWS),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(MIDNIGHT.proofServer, zkConfigProvider),
  };
}

// ── WalletProvider bridge (mirrors example-counter createWalletAndMidnightProvider) ──

async function buildWalletProvider(
  wallet:              WalletFacade,
  shieldedSecretKeys:  ledger.ZswapSecretKeys,
  dustSecretKey:       ledger.DustSecretKey,
  unshieldedKeystore:  UnshieldedKeystore,
): Promise<WalletProvider & MidnightProvider> {
  // Keys are derived immediately on init — no need to wait for full sync
  const state = await Rx.firstValueFrom(wallet.state());

  return {
    getCoinPublicKey() {
      return state.shielded.coinPublicKey.toHexString();
    },
    getEncryptionPublicKey() {
      return state.shielded.encryptionPublicKey.toHexString();
    },
    async balanceTx(tx, ttl?) {
      const recipe = await wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys, dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      const signedRecipe = await wallet.signRecipe(
        recipe,
        (payload) => unshieldedKeystore.signData(payload),
      );
      return wallet.finalizeRecipe(signedRecipe);
    },
    submitTx(tx) {
      return wallet.submitTransaction(tx) as any;
    },
  };
}

// ── Per-user key derivation ───────────────────────────────────────────────────

/**
 * Derives a user's Midnight secret key from their BIP-39 mnemonic.
 * Domain-separated from Cardano key derivation.
 * Returns 32 bytes — deterministic for the same mnemonic.
 */
export function deriveUserSecretKey(mnemonic: string): Uint8Array {
  const seed = mnemonicToSeedSync(mnemonic); // 64 bytes
  const hmac = createHmac('sha256', 'memorymint:midnight:sk:v1');
  hmac.update(seed);
  return new Uint8Array(hmac.digest());
}

/**
 * Computes the on-chain owner commitment for a given mnemonic.
 * Mirrors the Compact contract's ownerPublicKey(sk) function:
 *   persistentHash<Vector<2, Bytes<32>>>([pad(32, "memorymint:owner:"), sk])
 */
const _descriptor_bytes32 = new compactRuntime.CompactTypeBytes(32);
const _descriptor_ownerVec = new compactRuntime.CompactTypeVector(2, _descriptor_bytes32);
const OWNER_PREFIX = new Uint8Array([
  109, 101, 109, 111, 114, 121, 109, 105, 110, 116, 58, 111, 119, 110, 101, 114, 58,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
]); // "memorymint:owner:" padded to 32 bytes

export function computeOwnerCommitment(mnemonic: string): Uint8Array {
  const sk = deriveUserSecretKey(mnemonic);
  return compactRuntime.persistentHash(_descriptor_ownerVec, [OWNER_PREFIX, sk]) as Uint8Array;
}
